// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BOt85B_cdxU_CllKKzMY9RyIiAZSE9I',
    appId: '1:1094431091928:web:1f66fb2a49f2073447fbad',
    messagingSenderId: '1094431091928',
    projectId: 'kms-esaunggul',
    authDomain: 'kms-esaunggul.firebaseapp.com',
    storageBucket: 'kms-esaunggul.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdqjZnrM5WwqgtCBpILfiIGHdIUOjxcw',
    appId: '1:1094431091928:android:507438eb5d92ebfa47fbad',
    messagingSenderId: '1094431091928',
    projectId: 'kms-esaunggul',
    storageBucket: 'kms-esaunggul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RQ7e15MiPFSZ92dKUMlZVoxLMosDJ-c',
    appId: '1:1094431091928:ios:6275f6a57a73baf047fbad',
    messagingSenderId: '1094431091928',
    projectId: 'kms-esaunggul',
    storageBucket: 'kms-esaunggul.appspot.com',
    iosBundleId: 'com.example.kmsEsaunggul',
  );
}
